In [47]:
import numpy as np

def xyz2uvd(pts, paras, flip=1):
    # paras: [fx, fy, fu, fv]
    pts_uvd = pts.copy()
    pts_uvd = pts_uvd.reshape(-1, 3)
    pts_uvd[:, 1] *= flip
    pts_uvd[:, :2] = pts_uvd[:, :2] * paras[:2] / pts_uvd[:, 2:] + paras[2:]

    return pts_uvd.reshape(pts.shape).astype(np.float32)


def uvd2xyz(pts, paras, flip=1):
    # paras: (fx, fy, fu, fv)
    pts_xyz = pts.copy()
    pts_xyz = pts_xyz.reshape(-1, 3)
    pts_xyz[:, :2] = (pts_xyz[:, :2] - paras[2:]) * pts_xyz[:, 2:] / paras[:2]
    pts_xyz[:, 1] *= flip

    return pts_xyz.reshape(pts.shape).astype(np.float32)


In [8]:
center_xyz = np.loadtxt('./images/nyu/center_test_refined.txt')
center_xyz

NameError: name 'np' is not defined

In [4]:
center_xyz.shape

(8252, 3)

In [12]:
reshaped = center_xyz.reshape(-1, 3)
reshaped.shape

(8252, 3)

In [14]:
pts.reshape(-1, 3)

array([[0, 0, 0],
       [1, 1, 1]])

In [20]:
pts = np.array([
  [0, 0, 0],
  [1, 1, 1]
])

paras = (588.03, 587.07, 320., 240.)

uvd = xyz2uvd(center_xyz, paras)

[[-133.28715515  -12.86797142  761.99810791]
 [-134.04685974  -13.17334747  764.24127197]
 [-134.10357666  -13.0756321   764.19580078]
 ...
 [ -11.20250702 -248.05474854  978.31573486]
 [ -11.18813324 -248.47120667  979.79846191]
 [ -11.30259991 -248.34965515  978.96453857]]


In [23]:
uvd

array([[217.14299, 230.08606, 761.9981 ],
       [216.86035, 229.88058, 764.2413 ],
       [216.81058, 229.95505, 764.1958 ],
       ...,
       [313.26657,  91.14673, 978.31573],
       [313.2854 ,  91.12245, 979.79846],
       [313.2109 ,  91.06853, 978.96454]], dtype=float32)

In [26]:
uvd[:,0].max()

435.37183

In [27]:
uvd[:,1].max()

325.8304

In [1]:
pts.shape

NameError: name 'pts' is not defined

In [5]:
import numpy as np

a = np.array([
  [1, 1, 1]
])

b = np.array([
  [2, 2, 2]
])

stack = np.dstack((a,b))

print(stack)
stack.shape

[[[1 2]
  [1 2]
  [1 2]]]


(1, 3, 2)

In [19]:
import cv2

img = cv2.imread('../images/nyu/depth_1_0000001.png')
img[:,:,0] 
img[:,:,1]

array([[7, 7, 7, ..., 7, 7, 7],
       [7, 7, 7, ..., 7, 7, 7],
       [7, 7, 7, ..., 7, 7, 7],
       ...,
       [7, 7, 7, ..., 7, 7, 7],
       [7, 7, 7, ..., 7, 7, 7],
       [7, 7, 7, ..., 7, 7, 7]], dtype=uint8)

In [43]:
depth = np.asarray(img[:,:,0] + img[:,:,1] * 256, dtype=np.float32)

In [45]:
depth.shape

(480, 640)

In [46]:
depth[240][320]

1020.0

In [57]:
paras = (588.03, 587.07, 320., 240.)
center = np.array([-133.28715515137, -12.867971420288, 761.99810791016])
uvd = xyz2uvd(center, paras, flip=-1)
uvd

array([217.14299, 249.91394, 761.9981 ], dtype=float32)

In [58]:
depth[217][250]

761.0

In [38]:
import numpy as np
a = np.array([
  [
    [1,5,1],
    [2,6,2]
  ],
  [
    [3,7,3],
    [4,8,4]
  ],
])

In [39]:
a.shape

(2, 2, 3)

In [40]:
a[:,:,0]

array([[1, 2],
       [3, 4]])

In [41]:
a[:,:,1]

array([[5, 6],
       [7, 8]])

In [1]:
import numpy as np

mat = np.array([
  [1, 2],
  [3, 4],
  [1, 1]
])

print(np.asarray(mat < 5).nonzero())
print(np.where(mat < 5))

(array([0, 0, 1, 1, 2, 2], dtype=int64), array([0, 1, 0, 1, 0, 1], dtype=int64))
(array([0, 0, 1, 1, 2, 2], dtype=int64), array([0, 1, 0, 1, 0, 1], dtype=int64))


# Leitura do arquivo de profundidade

In [1]:
import numpy as np
import cv2

depth = np.loadtxt('../images/dataset/frame_0.txt')

depth_colormap = cv2.applyColorMap(cv2.convertScaleAbs(depth, alpha=0.03), cv2.COLORMAP_JET)

window = 'Depth'
cv2.namedWindow(window, cv2.WINDOW_NORMAL)
cv2.resizeWindow(window, 640, 480)
cv2.imshow(window, depth_colormap)
cv2.waitKey(0)
cv2.destroyWindow(window)